App_Blog/urls.py
from django.urls import path
from .import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreatBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('disliked/<pk>/', views.disliked, name='dislike_post'),
    path('my-blogs', views.MyBlog.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

App_Login/urls.py
from django.urls import path
from  .import views
app_name = 'App_login'
urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/',views.profile, name='profile'),
    path('user_change/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')
    facebook_id = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import  UserProfile

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic']

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login,authenticate,logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, UserProfileChange, ProfilePic
# Create your views here.
def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == "POST":
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    
    dict = {'form':form, 'registered':registered}
    return render(request, 'App_Login/signup.html',context=dict)

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    dict = {'form':form}
    return render(request, 'App_Login/login.html', context=dict)

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    
@login_required
def profile(request):
    return render(request,'App_Login/profile.html', context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
            return HttpResponseRedirect(reverse('profile'))

    return render(request, 'App_Login/change_profile.html', context={'form':form})

@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_Login/change_password.html',context={'form':form})

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_login:profile'))
    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})

templates/App_Login/change_password.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Change Password {% endblock %}
{% block content %}
{% if changed %}
<div class="alert alert-warning">
    Password Changed Successfully.
</div>
{% endif %}
<div class="main-content">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-6">
            <h2>Change Password:</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button type="submit" name="submit" class="btn btn-warning">Change Password</button>
            </form>
        </section>
    </section>
</div>

{% endblock content %}

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %}
{% block content %}
<div class="main-content">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-6">
            <h2>Change Profile:</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button type="submit" name="submit" class="btn btn-warning">Change</button>
            </form>
        </section>
    </section>
</div>
{% endblock content %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block content %}
<div class="main-content">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-6">
            <h2 class="text-center">Login</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <br>
                <button type="submit" name="submit" class="btn btn-primary">Login</button>
            </form>
            <br>
            <p>If you have not any account please register here. <a href="{% url 'App_login:signup' %}">Register Here</a></p>
        </section>
    </section>
</div>
{% endblock content %}

templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Profile Pic {% endblock %}
{% block content %}
<div class="main-content">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-6">
            <h2>Add your profile picture:</h2>
            <form method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button type="submit" name="submit" class="btn btn-primary">Add</button>
            </form>
        </section>
    </section>
</div>

{% endblock content %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title_block %} Profile {% endblock %}
{% block content %}
<div class="main-content">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-6">
            <h2>Your Profile</h2>
            {% if user.user_profile %}
            <img src="/media/{{ user.user_profile.profile_pic }}" class="img-circle" width="100px">
            {% else %}
            <img src="/media/profile_pics/profile.jpg" class="img-circle" width="100px">
            <br>
            <a href="{% url 'App_login:add_pro_pic' %}" class="btn btn-info btn-sm" >Change Profile Pic</a>
            {% endif %}
            <br>
            <br>
            <p>Username: {{ user.username }}</p>
            <p>Email: {{ user.email }} </p>
            <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
            <br>
            <a href="{% url 'App_login:user_change' %}" class="btn btn-warning" >Change Profile Info</a>
        </section>
    </section>
</div>
{% endblock content %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}
{% block content %}
{% if registered %}
    <div class="alert alert-success">
        Account Created Successfully! <a href="{% url 'App_login:login' %}">Login Here</a>
    </div>
{% else %}
<div class="main-content">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-6">
            <h2 class="text-center">Create New Account</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button type="submit" name="submit" class="btn btn-success" >Create Account</button>
            </form>
            <br>
            <p>Already have an account? <a href="{% url 'App_login:login' %}">Login Here</a></p>
        </section>
    </section>
</div>
{% endif %}
{% endblock content %}