App_Blog/urls.py
from django.urls import path
from .import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreatBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('disliked/<pk>/', views.disliked, name='dislike_post'),
    path('my-blogs', views.MyBlog.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import uuid
# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=200, verbose_name="put a title")
    slug = models.SlugField(max_length=265, unique=True)
    blog_content = models.TextField(verbose_name="what in your mind")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.blog_title

    def save(self):
        self.slug = slugify(self.blog_title+ '-' + str(uuid.uuid4()))
        super(Blog, self).save()

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField(null=True)
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-comment',)

    def __str__(self):
        return self.comment

class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_user')

    def __str__(self):
        return self.user + " Likes " + self.blog


App_Blog/forms.py
from django import forms
from App_Blog.models import Blog, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

App_Blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, DetailView, TemplateView, View, DeleteView, ListView
from App_Blog.models import Blog, Comment, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from App_Blog.forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
# Create your views here.

class CreatBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'App_Blog/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image',)

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'

@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    #liked and dislike portion
    already_liked = Likes.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    #end liked and dislike portion

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':slug}))

    return render(request, 'App_Blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked})

@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))

@login_required
def disliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))


class MyBlog(LoginRequiredMixin, TemplateView):
    template_name = 'App_Blog/my_blogs.html'


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title','blog_content','blog_image')
    template_name = 'App_Blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Blog:blog_details', kwargs={'slug':self.object.slug})

templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block content %}
<div class="main-content">
    <div class="row">
        <div class="col-sm-6">
            <h2>{{blog.blog_title}}</h2>
            <h4>Posted by: {{blog.author}}</h4>
            <i><h6>Publish On: {{blog.publish_date}}</h6></i>
            <i><h6>Updated On: {{blog.update_date}}</h6></i>
            <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comment</h6>
        </div>
        <div class="col-sm-6">
            <img src="/media/{{blog.blog_image}}" width="100%">
        </div>
        <p>
            {{blog.blog_content|linebreaks}}
        </p>
        {% if not liked %}
        <a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
            <i class="fa fa-thumbs-o-up" aria-hidden="true">Like</i>
        </a>
        {% else %}
        <a href="{% url 'App_Blog:dislike_post' pk=blog.pk %}">
            <i class="fa fa-thumbs-o-down" aria-hidden="true">Unlike</i>
        </a>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-sm-6">
            <hr>
            <h5>Comments:</h5>
            {% for comment in blog.blog_comment.all %}
                <p><a href="#">@{{comment.user}}</a> {{comment.comment}}<br> <h6>{{comment.comment_date}}</h6> </p>
            {% endfor %}
        </div>
        <div class="col-sm-6">
            <form method="POST">
                {% csrf_token %}
                {{comment_form|crispy}}
                <br>
                <button type="submit" name="submit" class="btn btn-primary">Comment</button>
            </form>
        </div>
    </div>

</div>

{% endblock %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block content %}
{% for blog in blogs %}
<h3>{{blog.blog_title}}</h3>
<h6><i>{{blog.publish_date}}</i></h6>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a></p>
    <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
    <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count }} Comments </h6>
  </div>
</div>
<hr>
{% endfor %}
{% endblock content %}

templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} {% endblock %}
{% block content %}
<div class="main-content">
    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-6">
            <h2 class="text-center">Write Your Blog Here</h2>
            <br>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" name="submit" class="btn btn-primary">Publish</button>
            </form>
        </section>
    </section>
</div>


{% endblock %}

templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block content %}
{% if blog.author == user %}
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type="submit" class="btn btn-secondary">Update</button>
    </form>
{% else %}
    <p>You are not allow to update this blog.</p>
{% endif %}

{% endblock %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} {{ user }} {% endblock %}
{% block content %}
    {% for blog in user.post_author.all %}
        <h3>{{blog.blog_title}}</h3>
        <h6>{{blog.publish_date}}</h6>
        <div class="row">
            <div class="col-sm-4">
                <img src="/media/{{blog.blog_image}}" width="100%">
            </div>
            <div class="col-sm-8">
                <p>{{blog.blog_content|range_filter|linebreaks}}</p>
                <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>
            </div>
        </div>
        <a href="{% url 'App_Blog:edit_blog' pk=blog.pk %}" class="btn btn-primary">Edit</a>
        <hr>
    {% endfor %}

{% endblock %}